### ISSUE TITLE
Prefer generic Activator.CreateInstance<T>()

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#102]

**Comment by brian-reichle** [comment]
Do you know of a case where `Activator.CreateInstance<T>()` works but `new T()` does not? should probably favor the latter :)

**Comment by JohanLarsson** [comment]
Good question and good timing, I was about to push, reverting.

**Comment by jnm2** [comment]
> Do you know of a case where `Activator.CreateInstance<T>()` works but `new T()` does not? should probably favor the latter :)

Generics, when `T` does not have a `new()` constraint or a `struct` constraint.
