### ISSUE TITLE
Use correct obj parameter when calling methodInfo.Invoke(obj, ...)

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#103]
- [x] Null for static
- [x] Not null for instance
- [x] Check type for insatnce.

**Comment by brian-reichle** [comment]
things could get weird if the target type is a nullable struct ... but probably not much need to use reflection in that case :)

**Comment by JohanLarsson** [comment]
Adding testcases, thanks!

**Comment by brian-reichle** [comment]
Probably more an issue when it comes time to validate the argument types.

**Comment by brian-reichle** [comment]
The weirdness I was thinking of is related to the boxing of nullable types. When a nullable type is boxed, you will either get a boxed copy of the underlying type or null.

So at runtime, the following two are equivalent:
```csharp
typeof(int?).GetMethod(nameof(Nullable<int>.GetValueOrDefault), Type.EmptyTypes).Invoke(null, null)
typeof(int?).GetMethod(nameof(Nullable<int>.GetValueOrDefault), Type.EmptyTypes).Invoke(new int?(), null)
```

As are the following two:
```csharp
typeof(int?).GetMethod(nameof(Nullable<int>.GetValueOrDefault), Type.EmptyTypes).Invoke(42, null)
typeof(int?).GetMethod(nameof(Nullable<int>.GetValueOrDefault), Type.EmptyTypes).Invoke((int?)42, null)
```

**Comment by JohanLarsson** [comment]
I'm adding more test cases.
