### ISSUE TITLE
Fix for REFL001 

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#114]
- [x] When assigned to `var`

**Comment by brian-reichle** [comment]
Are you planning on enforcing that it's cast to the constructed type? or just something assignable from the constructed type? what if the constructed type is not visible? what if the most specific base type that is externally visible is `object`?

**Comment by JohanLarsson** [comment]
Good points, we add checks that the type is visible.

**Comment by jnm2** [comment]
@JohanLarsson I'd never want to be forced to be unnecessarily specific about the type. Using `IEnumerable<int>` even when I could be using `List<int>` makes the reflection code more robust, don't you think?

**Comment by JohanLarsson** [comment]
We will not nag if there is a cast of course. Being more specific than `object` is a good thing though. My thinking is we cast it when created to make it clear.

**Comment by jnm2** [comment]
> Being more specific than `object` is a good thing though.

I'm sure; why would this be? I might only want to invoke members via reflection, or I might not even need to invoke members.

**Comment by jnm2** [comment]
> It is a decent postfix opportunity though, we can make it hidden or a refactroing.

Okay, I do like this idea.
