### ISSUE TITLE
REFL019 "No member matches the types" message is incorrect

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#122]
It's really cool that it noticed that I was still using `typeof(Dictionary<string, object>)` after changing the target method parameter to `IReadOnlyDictionary<string, object>`, and it's correct that I'd want to fix that, but it's not correct that the method does not match the types.

The default binder will do overload resolution and can pick a method with an `IReadOnlyDictionary<string, object>` parameter even if you specify `Dictionary<string, object>` in that position.

**Comment by JohanLarsson** [comment]
Code please!

**Comment by jnm2** [comment]
```cs
class C
{
    void M(IReadOnlyDictionary<string, object> p)
    {
        typeof(C).GetMethod(
            nameof(M),
            BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly,
            null,
            new[] { typeof(Dictionary<string, object>) }, // Matches the method using this type
            null);
    }
}
```
