### ISSUE TITLE
Prefer RuntimeHelpers.RunClassConstructor over ConstructorInfo.Invoke

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#124]
Shouldn't use ConstructorInfo.Invoke to call a static constructor, if you need to ensure that the class constructor has run, then use [RuntimeHelpers.RunClassConstructor](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.compilerservices.runtimehelpers.runclassconstructor?redirectedfrom=MSDN&view=netframework-4.7.2#System_Runtime_CompilerServices_RuntimeHelpers_RunClassConstructor_System_RuntimeTypeHandle_) instead.

From: https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/109#issuecomment-425623004

**Comment by JohanLarsson** [comment]
Why is it better?

**Comment by brian-reichle** [comment]
The static constructor is only supposed to run once, RunClassConstructor will maintain that promise but ConstructorInfo.Invoke will not (which will likely corrupt both the application and your soul.)

https://dotnetfiddle.net/UkbHXR

I'm not sure ConstructorInfo.Invoke will even protect against concurrent calls from multiple threads.
