### ISSUE TITLE
REFL004 should suggest fixes for op_Explicit and op_Implicit overloads

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#128]
```c#
class C
{
    void M()
    {
        typeof(C).GetMethod("op_Explicit");
    }

    public static explicit operator int(C c) => default;
    public static explicit operator C(int c) => default;
}
```

Gives this diagnostic, but no fixes:

> REFL004 More than one member is matching the criteria.

Fixes I'd expect:

```c#
typeof(C).GetMethod("op_Explicit", new[] { typeof(C) })
```

```c#
typeof(C).GetMethod("op_Explicit", new[] { typeof(int) })
```

**Comment by jnm2** [comment]
However in this scenario, disambiguation is impossible without specifying a custom binder. In practice, I'd just use GetMethods() and filter manually.

```c#
class C
{
    void M()
    {
        typeof(C).GetMethod("op_Explicit");
    }

    public static explicit operator int(C c) => default;
    public static explicit operator string(C c) => default;
}
```

**Comment by jnm2** [comment]
In this scenario, I'm thinking it would be a good think to offer one fix even though no fix can be offered for the other two overloads. The only potential downside is that the user might think that the analyzer is saying that there is only one overload she'd want to use.

```c#
class C
{
    void M()
    {
        typeof(C).GetMethod("op_Explicit");
    }

    public static explicit operator int(C c) => default;
    public static explicit operator string(C c) => default;
    public static explicit operator C(int c) => default;
}
```

Single fix offered:

```c#
typeof(C).GetMethod("op_Explicit", new[] { typeof(int) })
```

**Comment by JohanLarsson** [comment]
I think for the last case it is probably best to not offer a fix as it would be a guess.
For the second case the warning is very good drawing attention to the problem.

**Comment by jnm2** [comment]
@JohanLarsson What do you mean about it being a guess? The single fix we could offer for the last case is the only possible option using `GetMethod` that doesn't throw AmbiguousMatchException.

**Comment by JohanLarsson** [comment]
Yes, that is correct, I worded it poorly, meant I agree with you in that there is a risk that offering a fix means the fix is applied without much thought.
