### ISSUE TITLE
Validate AssemblyVersion and AssemblyFileVersion

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#13]

**Comment by JohanLarsson** [comment]
You want them to be in sync?

**Comment by jnm2** [comment]
I don't think so- I was thinking we should report errors for non-version strings. `1.0.*` is specially understood by the compiler.

**Comment by JohanLarsson** [comment]
If you are bored you can dump some valid and invalid cases as test ammo.

**Comment by brian-reichle** [comment]
How does this compare to CS7034 and CS7035?

**Comment by jnm2** [comment]
Oh duh... do these diagnostics happen as you type or only on build?

**Comment by brian-reichle** [comment]
Just confirmed, it happens as you type.

**Comment by JohanLarsson** [comment]
Is this issue redundant then?
Is there something built in for `TryParse` of the version string?

**Comment by brian-reichle** [comment]
Yeah, I think it's redundant.

**Comment by jnm2** [comment]
Thanks @brian-reichle, good to know!
