### ISSUE TITLE
Warn if GetType is not checked for null unless throwOnError is true

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#14]
Type.GetType and Assembly.GetType, suggest adding null check or adding `throwOnError: true`.

**Comment by JohanLarsson** [comment]
Maybe warn if `throwOnError: true` is missing?

**Comment by jnm2** [comment]
I wouldn't want it to warn here:

```c#
var type = Type.GetType("foo");
if (type != null)
{
    // ...
}
```

**Comment by JohanLarsson** [comment]
Wrote an analyzer that checks for the simplest case, nullable reference types are coming!

**Comment by jnm2** [comment]
See https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/155.
