### ISSUE TITLE
REFL033 "Use more specific types in the filter" should have a more specific message

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#144]
It would be nice if it could say something like, "Use the exact type in the method signature (IReadOnlyDictionary<string, object>) instead of Dictionary<string, object>."

**Comment by JohanLarsson** [comment]
Use the same type as in the method signature.?

**Comment by jnm2** [comment]
Yes. It wasn't immediately obvious to me that there was a difference in the case I hit.

**Comment by JohanLarsson** [comment]
Never stop reporting these!

**Comment by jnm2** [comment]
> Use the same type as the parameter.

This sounds good too!

**Comment by JohanLarsson** [comment]
I'm changing it so that the location of the argument is flagged and adding a fix.
