### ISSUE TITLE
REFL031 "Use correct generic parameters" should have a more specific message

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#145]
First of all, the generic _parameter_ is the `T` in the class declaration; the generic _argument_ is the type I specify to satisfy that parameter. So you use whatever parameters the class declares and you have no choice about that. What you do have a choice about is which arguments to use. So it should be, "Use correct generic arguments."

Can it be more specific and say whether the wrong number of generic arguments was specified or whether a particular constraint on a particular parameter was violated?

**Comment by JohanLarsson** [comment]
The class is named `REFL031UseCorrectGenericArguments` refactoring accident? Thanks for reporting!
We can be more specific, updating to say if count did not match. When argument does not match we indicate the first argument not satisfying the parameter's constraints.

**Comment by jnm2** [comment]
What about the word 'valid' instead of 'correct'?

**Comment by JohanLarsson** [comment]
Updating, keep it coming!
