### ISSUE TITLE
REFL001 should not nag here

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#159]
```cs
private static readonly TBox DefaultValueInstance = Activator.CreateInstance<TBox>();
```

**Comment by SonicGD** [comment]
Same problem with 

```cs
var restModel = Activator.CreateInstance<TRestModel>();
```

**Comment by JohanLarsson** [comment]
Dumb bug, sorry about that, thanks for reporting!

**Comment by JohanLarsson** [comment]
@SonicGD this analyzer is still in very early stages, if you have time write issues for where we dumb things and don't trust what the analyzer says. Maybe after 1 000 issues we get to a point where the analyzer is more helpful than annoying.

**Comment by SonicGD** [comment]
Of course, i understand that. For now i've only find this issue. Also, analyzer already helped me with some "GetMethod" suggestions, so it's not that useless :) If i find anything - i will create issue. And thank you for your job =)
