### ISSUE TITLE
REFL036 message should something like "Pass 'throwOnError: true' or check if null"

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#163]
If you're planning for the type to exist, it's preferable to pass `throwOnError: true` so that an intelligent assertion message (not NullReferenceException) results from that assumption being violated.

**Comment by jnm2** [comment]
See also https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/155.

**Comment by jnm2** [comment]
Can you add a refactoring to insert `throwOnError: true` at the same time, or is that a separate issue?

**Comment by JohanLarsson** [comment]
Yes we can add the fix.

**Comment by JohanLarsson** [comment]
Risky to append a feature request to an issue like this, I miss a large % of things :)

**Comment by JohanLarsson** [comment]
I wrote it so that it offers to change explicit `throwOnNull: false` to true or add if missing.
