### ISSUE TITLE
GetProperty/Event should be suggested even when the existence is not known

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#164]
`GetMethod("get_Foo")` should suggest `GetProperty("Foo").GetMethod` unless the analyzer can positively prove that the property or event does not exist (extremely rare). Right now, if the analyzer doesn't know for sure, it stops offering the refactoring.

**Comment by JohanLarsson** [comment]
We have tests for this [here](https://github.com/DotNetAnalyzers/ReflectionAnalyzers/blob/master/ReflectionAnalyzers.Tests/REFL014PreferGetMemberThenAccessorTests/CodeFix.cs#L336-L373). We need repro code showing the bug.

**Comment by jnm2** [comment]
The repro code for https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/189#issuecomment-439706200 is similar to what we could use here. Let me know if I can help with this.
