### ISSUE TITLE
'Prefer GetProperty' is not offered when types are specified

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#165]
This gives no REFL014:

```c#
GetMethod("get_Foo", theBindingFlags, null, Type.EmptyTypes, null)
```

Would expect:
```c#
GetProperty("Services", theBindingFlags, null, typeof(TheReturnType), Type.EmptyTypes, null).GetMethod
```

There *is* already such a refactoring and analyzer on this:

```c#
GetMethod("get_Foo", theBindingFlags)
```

Which refactors to:

```c#
GetProperty("Services", theBindingFlags).GetMethod
```

Same for GetEvent.

**Comment by JohanLarsson** [comment]
// Not handling when explicit types are passed for now. No reason for this other than that I think it will be rare.

**Comment by jnm2** [comment]
https://github.com/DotNetAnalyzers/ReflectionAnalyzers/blob/d70c469d650eccaf9edd5fff21903482d2105175/ReflectionAnalyzers.Tests/REFL014PreferGetMemberThenAccessorTests/CodeFix.cs#L257

Hmm, This is a problem for me. Having no refactoring is better than having a refactoring that strips out the explicit types. There is never a time where removing explicit types would be okay with me; therefore, the only thing I could do after using this refactoring and seeing the result is to undo the refactoring.

**Comment by jnm2** [comment]
d70c469 is about events, whereas this issue is only about properties.

**Comment by JohanLarsson** [comment]
There were two commits: here is the other https://github.com/DotNetAnalyzers/ReflectionAnalyzers/commit/55a1e5e55a2390e9a0ac98937e56935f15ae413b

**Comment by JohanLarsson** [comment]
We need a repro for what is not working.

**Comment by jnm2** [comment]
Oh, good! The commit you just linked does close this issue:

https://github.com/DotNetAnalyzers/ReflectionAnalyzers/commit/55a1e5e55a2390e9a0ac98937e56935f15ae413b#diff-fd34d34f0d0cad4279760679053e115aR17

I was confused by the events commit closing this issue and having nothing else to look at.
