### ISSUE TITLE
REFL013 should probably report using the provided type arguments.

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#166]
```csharp
public static class Foo
{
    public static void Bar(int? value)
    {
        typeof(int?).GetMethod("Value");
    }
}
```

Reports the following error on `GetMethod`:

> Error REFL013 The type int? has a member named Value of type SubstitutedPropertySymbol.

Should probably be:

> Error REFL013 The type int? has a property named Value of type int.

**Comment by JohanLarsson** [comment]
I was lazy there, fixing.

**Comment by JohanLarsson** [comment]
Shortened it to:
> Error REFL013 The type int? has a property named Value.
