### ISSUE TITLE
Nullable<T>.GetType() behaves differently to other types.

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#167]
```csharp
public static void Bar(int? value)
{
    value.GetType().GetMethod("Value");
}
```

This produces the following error:

> Error REFL013 The type int? has a member named Value of type SubstitutedPropertySymbol.

Which suggests that the analyzer thinks `value.GetType()` will be `typeof(int?)`, but this will not be the case. GetType() is inherited from object and not overridden (because it can't be) which means that the value needs to be boxed before `GetType()` can be called, and boxing a `Nullable<>` value will either result in a boxed instance of the underlying type (resulting in `typeof(int)`) or null (resulting in a NullReferenceException).

**Comment by JohanLarsson** [comment]
This is a nice example of where #169 will make the code clearer.
