### ISSUE TITLE
Should we warn people against calling GetType on a struct?

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#169]
Structs are always 'sealed' so if you know that a given type will be a struct, then you can use 'typeof' instead (which avoids boxing and is less likely to produce unexpected results if the type happens to be nullable).

https://dotnetfiddle.net/7Z8kMw

```csharp
int? a = ...
var type = a.GetType();
```

should become:

```csharp
int? a = ...
var type = typeof(int?);
```

Not sure if this is within scope for ReflectionAnalyzers, seems borderline to me.

**Comment by pdelvo** [comment]
This should probably also apply to sealed reference types as long as they are not anonymous.

**Comment by brian-reichle** [comment]
@jnm2, yes on enums and sealed delegates, but not `MulticastDelegate` or `Delegate` itself.
