### ISSUE TITLE
REFL003 is overly permissive with TupleTypes

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#170]
The tuple type syntax is really just c# magic around `ValueTuple<>`. Reflection only sees the `Item1`, `Item2`, etc members and not the names that C# gives them. So `GetField` will return null in the following code, but REFL003 says it's ok.

```csharp
static void Main(string[] args)
{
    var x = Baz();

    Console.WriteLine(x.GetType().GetField("a").Name);
}

static (int a, int b) Baz() => default;
```

Should suggest using "Item1" instead of "a".

**Comment by jnm2** [comment]
Also, `Item8` is legal syntax in C# but in metadata, fields higher than `Item7` are nested in the `Rest` field.

**Comment by JohanLarsson** [comment]
@jnm2 > `Item7` is a warning right? Error more correct but VS handles does not handle errors well ime.

**Comment by jnm2** [comment]
@JohanLarsson reflection trying to access fields by the names `Item8` and higher is known to fail at runtime because the fields do not exist in metadata, so an error is most appropriate. I haven't heard of a reason why errors aren't well handled, but a warning would still be useful too.

Also, can you test that `GetField("Rest")` gives no warning if the type is ``ValueTuple`8``?

**Comment by jnm2** [comment]
> you can try setting everything to error in ruleset to simulate it

I have done this for a good number of rules and haven't noticed anything strange about it. Maybe that was specific for WPF?

**Comment by JohanLarsson** [comment]
I'll ping you next time I have weirdness.

**Comment by JohanLarsson** [comment]
I used REFL003 for > `Item7`. Did not write a fix for now, don't think reflection on tuples will be common. Write issues if there is a need for a fix or other things.

**Comment by brian-reichle** [comment]
I imagine an automated fix would be easy up to `Item7` and then quickly become a nightmare :)

I have used reflection over `Tuple<>` types, but that was to generate some dynamic expression trees. I can also see it being used when emitting, but not so much for direct "invoking".

**Comment by JohanLarsson** [comment]
Yes, fix up to `Item7` should be easy and we could perhaps start with that if a fix is needed.
