### ISSUE TITLE
Allow Type.DefaultBinder

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#171]
```cs
typeof(C).GetMethod("M", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly, Type.DefaultBinder, Type.EmptyTypes, null)
```

Today we check known signatures and allow only `null` passed as binder. We should allow `Type.DefaultBinder` right?

**Comment by jnm2** [comment]
I'd expect any binder to be allowed, and the diagnostics to bail without reporting if you use anything other than `null` or `Type.DefaultBinder`.

**Comment by JohanLarsson** [comment]
Yes that is the plan, currently we bail on `Type.DefaultBinder` easy fix.
