### ISSUE TITLE
Erroneous REFL037 'The type does not exist' warnings

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#187]
```c#
obj.GetType().Assembly.GetType("Microsoft.VisualStudio.Design.VSTypeResolutionService+AssemblyEntry", throwOnError: true)

typeof(DataObject).Assembly.GetType("System.Windows.Forms.DataObject+OleConverter", throwOnError: true)

typeof(XRDesignPanel).Assembly.GetType("DevExpress.XtraReports.UserDesigner.Native.INestedServiceProvider", throwOnError: true)

typeof(FileDialog).Assembly.GetType("System.Windows.Forms.FileDialog+VistaDialogEvents", throwOnError: true)
```

**Comment by jnm2** [comment]
##### ReflectionAnalyzersRepdo.csproj

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ReflectionAnalyzers" Version="0.1.17-dev" PrivateAssets="all" />
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

</Project>
```

##### Program.cs

```c#
using System;
using System.Windows.Forms;

namespace ReflectionAnalyzersRepro
{
    public static class Program
    {
        public static void Main()
        {
            Console.WriteLine(typeof(DataObject).Assembly.GetType("System.Windows.Forms.DataObject+OleConverter", throwOnError: true));

            Console.WriteLine(typeof(FileDialog).Assembly.GetType("System.Windows.Forms.FileDialog+VistaDialogEvents", throwOnError: true));
        }
    }
}
```

Prints:

```
System.Windows.Forms.DataObject+OleConverter
System.Windows.Forms.FileDialog+VistaDialogEvents
```

But analyzer gives "REFL037 The type does not exist." on both types.

This is likely because the analyzer is failing to recognize that the referenced System.Windows.Forms.dll is a ref assembly, a compile-time-only shim with no private types and members.

**Comment by jnm2** [comment]
The reason why your tests don't repro is probably because you're referencing the actual runtime System.Windows.Forms in the compilation created by your test rather than doing what the C# SDK does and referencing the compile-only reference assembly for net472.

**Comment by jnm2** [comment]
Make sure the compilation created by your test references `C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\System.Windows.Forms.dll` and not `C:\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Windows.Forms.dll` or `C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Windows.Forms\v4.0_4.0.0.0__b77a5c561934e089\System.Windows.Forms.dll`.

**Comment by JohanLarsson** [comment]
https://github.com/dotnet/roslyn/blob/master/docs/features/refout.md#definition-of-ref-assemblies
