### ISSUE TITLE
'Prefer GetEvent' sets nameof to wrong member

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#189]
0.1.17-dev. Same situation as https://github.com/DotNetAnalyzers/ReflectionAnalyzers/issues/96.

```c#
class Repro
{
    void M()
    {
        typeof(Foo).GetMethod("add_Bar", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly);
    }
}
```

In a separate assembly that is *binary*-referenced, not project-referenced (you can generate binary references on the fly with Roslyn in your test suite):

```c#
public interface IFoo
{
    event EventHandler Bar;
}

public class Foo : IFoo
{
    // To make sure the test is effective, assert that ReflectionAnalyzers *can’t* see this member:
    internal event EventHandler Bar;

    event EventHandler IFoo.Bar
    {
        add { }
        remove { }
    }
}
```

After 'Prefer GetEvent', it references the wrong event:

```c#
typeof(Foo).GetEvent(nameof(IFoo.Bar), BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).AddMethod;
```

Should be:

```c#
typeof(Foo).GetEvent("Bar", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).AddMethod;
```

**Comment by JohanLarsson** [comment]
>you can generate binary references on the fly with Roslyn in your test suite

Do you have sample code?

**Comment by jnm2** [comment]
Here is some: https://github.com/DotNetAnalyzers/ReflectionAnalyzers/compare/master...jnm2:binary_reference_test
