### ISSUE TITLE
Should GetMethod("get_Foo") be suggested instead of GetProperty("foo").GetGetMethod()?

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#19]
Or vice versa?

**Comment by JohanLarsson** [comment]
I think `GetProperty("Foo").GetMethod` reads clearer, dunno if there is a perf difference in doing `GetMethod("get_Foo")`?

If there is a difference it will likely not matter.

**Comment by jnm2** [comment]
I agree. A refactoring could potentially be nice if there's not a preferred direction.

**Comment by jnm2** [comment]
@brian-reichle I believe there is no requirement and it's up to the style of each compiler.

**Comment by JohanLarsson** [comment]
Analyzer is done for this, did not finish the fix. Gf had dinner ready so I had to leave it.
