### ISSUE TITLE
Minimal binding flags

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#190]
Should probably ensure that if the flags are provided to a GetX method, they include `Public`, `NonPublic` or both, even if no metadata information about the target is available. The runtime won't throw an exception, but it also won't match anything, so I think it provides a sufficiently strong indicator of a bug.

Same thing for the `Static` & `Instance` pair.

```csharp
// Should specify Instance and/or Static
obj.GetType().GetMethod("Foo", BindingFlags.Public);

// Should specify Public and/or NonPublic
obj.GetType().GetMethod("Foo", BindingFlags.Static);

// all good
obj.GetType().GetMethod("Foo", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Static);
obj.GetType().GetMethod("Foo", BindingFlags.Public | BindingFlags.Instance | BindingFlags.Static);
```

**Comment by JohanLarsson** [comment]
Should we use [REFL008](https://github.com/DotNetAnalyzers/ReflectionAnalyzers/blob/master/documentation/REFL008.md) for this?

**Comment by brian-reichle** [comment]
I would go with a new id, it feels like conceptually different scenario to me. (nonsensical flags vs no flags provided)

**Comment by JohanLarsson** [comment]
How should we word the title of the new ID?

**Comment by brian-reichle** [comment]
> REFLXXX - Insufficient flags

> These flags are insufficient to match any members.

**Comment by JohanLarsson** [comment]
We are lucky to have you!
