### ISSUE TITLE
Validate DefaultMemberAttribute

### ISSUE THREAD

**Issue by brian-reichle** [DotNetAnalyzers/ReflectionAnalyzers#193]
Should validate that member specified by the DefaultMemberAttribute actually exists.

```csharp
[DefaultMember("Bar")]
public class Foo
{
    public int Value { get; set; }
}
```

**Comment by jnm2** [comment]
Makes me think of https://docs.microsoft.com/dotnet/api/system.componentmodel.defaultpropertyattribute and https://docs.microsoft.com/dotnet/api/system.componentmodel.defaulteventattribute which are not in the Reflection namespace.

**Comment by brian-reichle** [comment]
@JohanLarsson, It's used by InvokeMember when the empty string is provided for the member name.

@jnm2, I though of those too, but I'm not sure if we should start branching out into non-reflection attributes that happen to specify members by name, as that list could get quite large and diverse (which reminds me, I should create an issue in WpfAnalyzers for the [DependsOnAttribute](https://docs.microsoft.com/en-us/dotnet/api/system.windows.markup.dependsonattribute?view=netframework-4.7.2) :))
