### ISSUE TITLE
Codefix: generate contents of GetX

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#20]
List all members in for example `GetMethod()` and generate name, bindingflags, types etc.

**Comment by JohanLarsson** [comment]
We add missing binding flags now.

**Comment by JohanLarsson** [comment]
#1

**Comment by jnm2** [comment]
> We add missing binding flags now.

No binding flags fix is offered for `typeof(Type).GetMethod(nameof(Type.GetTypeFromHandle))`.

**Comment by jnm2** [comment]
Also, no binding flags warning is given here, where the type is unknowable to the analyzer, but it's still important to make the user pick them (maybe fix to `Public | Static | Instance` to keep the same behavior but make it explicit):

`ownerType.GetMethod(nameof(CreateViewModel), new[] { typeof(Type), dictionaryType })`
