### ISSUE TITLE
Suggest CustomAttributes instead of GetCustomAttribute* which runs arbitrary code

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#22]
Types loaded in a reflection-only context enforce this at runtime, but for all types it's still an optimization and possibly a security improvement.

**Comment by JohanLarsson** [comment]
> which runs arbitrary code
What does ^ mean?
Can you post sample code of how you want the warning and fix?

**Comment by jnm2** [comment]
@JohanLarsson GetCustomAttribute/s dynamically instantiates the attribute which runs its constructor. CustomAttributeData fully describes the specified attributes without dynamically invoking.

On phone, but ping me if I forget examples.

**Comment by JohanLarsson** [comment]
ping for examples

**Comment by jnm2** [comment]
Given:

```c#
[DefaultProperty("Test")]
public class Foo
{
    public int Test { get; set; }
}

// Executes the attribute's constructor
var defaultPropertyName = typeof(Foo).GetCustomAttribute<DefaultPropertyAttribute>()?.Name

// Does not execute the attribute’s code
var defaultPropertyName = (string)typeof(Foo).GetCustomAttributesData()
    .FirstOrDefault(a => a.AttributeType == typeof(DefaultPropertyAttribute))
    ?.ConstructorArguments[0].Value;
```

How that I'm looking at it, even though the CustomAttributeData is safer (and the only option if the type is loaded in a reflection-only context), it's very complicated to make sure you have the right constructor and pull the right argument in a robust way.

So while the refactoring could be cool, I'm not confident recommending this in cases where you need to read properties off the attribute.
