### ISSUE TITLE
Can install these packages as extensions?

### ISSUE THREAD

**Issue by Donaut** [DotNetAnalyzers/ReflectionAnalyzers#291]
Hello,

The problem is that i want to use it at my work place but i cannot just spam the application with nuget packages. Can install it globaly or as a visual studio extension?

**Comment by JohanLarsson** [comment]
There is a VSIX project that I've used for debugging. <https://github.com/DotNetAnalyzers/ReflectionAnalyzers/blob/master/ReflectionAnalyzers.Vsix/ReflectionAnalyzers.Vsix.csproj>

Try building and installing it. It is not published in the Visual Studio Extension store or what-the-name-is.

**Comment by Donaut** [comment]
Thanks for the qucik response i try:D

**Comment by JohanLarsson** [comment]
If it does not work we should fix it so don't hesitate to report if it is broken.
