### ISSUE TITLE
Suggest nameof where possible

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#3]

**Comment by jnm2** [comment]
I expected this to handle `typeof(Dictionary<string, object>).GetMethod("Add")` by suggesting `nameof(Dictionary<string, object>.Add)`, but nothing is suggested. New issue or reopen?

**Comment by JohanLarsson** [comment]
New issue! Nicer with focused issues that we can close fast.
