### ISSUE TITLE
Analyzer: BindingFlags order

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#30]
OCD analyzer for max consistency.

**Comment by JohanLarsson** [comment]
Maybe require `BindingFlags.Public | BindingFlags.Static` to be consistent with `public static`?

**Comment by jnm2** [comment]
If you'd do this for BindingFlags, wouldn't you do this for any flags enum?

**Comment by JohanLarsson** [comment]
Valid point, I wrote it for one simple case and made it default hidden.
