### ISSUE TITLE
Analyzer: warn when GetX by name returns wrong symbol

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#35]
Example GetMethod("Foo") when there is a property named `Foo`

**Comment by jnm2** [comment]
What if there are .NET language that can overload by return type or something where this is legal?

**Comment by JohanLarsson** [comment]
The analyzers are for csharp only. I probably don't get the question.

**Comment by jnm2** [comment]
@JohanLarsson The analyzers may be for C#, but the types they are reflecting over may have been compiled by another language. The IL spec doesn't care if names are reused by members.

**Comment by brian-reichle** [comment]
It's probably better to assert that the Foo method exists rather than the the Foo property does not. (assuming you are able to identify the type).

**Comment by jnm2** [comment]
@brian-reichle I'm pretty sure there isn't any restriction on accessor names.
