### ISSUE TITLE
Analyzer: warn on duplicate binding flags

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#40]
```cs
GetMethod("Foo", BindingFlags.Public | BindingFlags.Public | BindingFlags.Instance)
```

**Comment by JohanLarsson** [comment]
Do you want the analyzer removed or expanded?

**Comment by jnm2** [comment]
It feels like it doesn't belong here. Ideally there'd be a general C# analyzer with things like this in DotNetAnalyzers or roslyn-analyzers, right?

**Comment by jnm2** [comment]
Maybe at https://github.com/dotnet/roslyn-analyzers/blob/master/src/Microsoft.CodeQuality.Analyzers/Microsoft.CodeQuality.Analyzers.md?

**Comment by JohanLarsson** [comment]
Go ahead and make a PR!
