### ISSUE TITLE
Check MethodInfo.Invoke return type

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#49]
```cs
var bar = (int)typeof(Foo).GetMethod("Bar").Invoke();
```

**Comment by brian-reichle** [comment]
Maybe only when we can't be certain it won't match. If the target method can be identified and is defined in the same assembly, then do we really need to check the return for null? (or perhaps have this situation reported with a different rule id so the project can decide :))

**Comment by JohanLarsson** [comment]
I don't understand how you mean.

My thinking is if we know the return type of the method we check the cast of the result or check that it is not used for anything if it is a `void` method.

**Comment by brian-reichle** [comment]
oh, I thought you meant check that GetMethod wasn't returning null. :)
