### ISSUE TITLE
REFL005 should not care about Instance and Static in GetNestedType

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#50]
```cs
namespace RoslynSandbox
{
    using System.Reflection;
    using NUnit.Framework;

    class Foo
    {
        internal static class Bar
        {
        }
    }

    class Tests
    {
        [Test]
        public void SomeTest()
        {
            Assert.NotNull(typeof(Foo).GetNestedType(nameof(Foo.Bar), BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
        }
    }
}
```

The msdn docs are not awesome [here](https://docs.microsoft.com/en-us/dotnet/api/system.type.getnestedtype?view=netframework-4.7.2):
> A bitmask comprised of one or more BindingFlags that specify how the search is conducted.

**Comment by jnm2** [comment]
A nested type is definitely not an instance member. There's a sense in which it's static, but the flag would be logically redundant.
