### ISSUE TITLE
Are BindingFlags.DeclaredOnly and BindingFlags.FlattenHierarchy redundant when calling GetNestedType?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#53]
@jnm2 you know this right?

**Comment by jnm2** [comment]
That's correct, quick test verifies this. In fact, these flags are redundant for all members except with public (not protected) instance members.

**Comment by JohanLarsson** [comment]
FlattenHierarchy is needed for bringing up static members from base classes no?`

**Comment by jnm2** [comment]
Static members are never brought up from base classes, as far as I know. FlattenHierarchy is geared towards tracking instance state.

**Comment by JohanLarsson** [comment]
But the docs answer the question:
> Nested types are not returned.
So the flag is redundant.

**Comment by jnm2** [comment]
Oh, thanks for setting me straight!

**Comment by JohanLarsson** [comment]
The analyzer will set us all straight when we forget in the future.
