### ISSUE TITLE
REFL014 ignores accessibility

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#58]
With this code (note the BindingFlags.NonPublic):

```c#
typeof(DbSet).GetMethod("get_InternalSet", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly)
```

This is an invalid refactoring:

> REFL014 Prefer typeof(DbSet).GetProperty(nameof(DbSet.InternalSet), BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).GetMethod

A valid refactoring:

```c#
typeof(DbSet).GetProperty("InternalSet", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly).GetGetMethod(nonPublic: true)
```

**Comment by JohanLarsson** [comment]
Derp, dumbed that one, thanks for the issue!

**Comment by JohanLarsson** [comment]
```cs
[Test]
public void Test()
{
    foreach (var type in typeof(string).Assembly.GetTypes())
    {
        foreach (var property in type.GetProperties(BindingFlags.NonPublic | BindingFlags.Instance))
        {
            Console.WriteLine($"{type}.{property}");
            Console.WriteLine(type.GetMethod("get_" + property.Name, BindingFlags.NonPublic | BindingFlags.Instance)?.Name ?? "null");
            Console.WriteLine(property.GetMethod?.Name ?? "null");
            return;
        }
    }
}
```
[Fiddle](https://dotnetfiddle.net/6YfHgv)

Prints:
```
System.AggregateException.Int32 InnerExceptionCount
get_InnerExceptionCount
get_InnerExceptionCount
```

**Comment by jnm2** [comment]
The problematic part is `nameof(DbSet.InternalSet)`. The compiler won't compile that because InternalSet is internal in a separate assembly.

I *thought* `GetMethod` was also a problem at runtime, but apparently not. I didn't actually get that far because the snippet doesn't compile.

**Comment by JohanLarsson** [comment]
Fixed now.
