### ISSUE TITLE
Check bindingflags when doing GetX

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#6]
- [x] GetConstructor
- [x] GetEvent
- [x] GetField
- [x] GetMember
- [x] GetMethod
- [x] GetNestedType
- [x] GetProperty

**Comment by JohanLarsson** [comment]
For the plural versions we can only warn if we detect that it returns empty array.

**Comment by brian-reichle** [comment]
Is the plan to assert things like Public vs NonPublic based on the detected visibility of the target? If so, then maybe permit both being provided together. I have encountered a situation in the past where public vs private depended on the version of the framework the code was running against. (using reflection to access a private member that was later made public)

**Comment by jnm2** [comment]
I too have scenarios where I was glad I used both.

**Comment by JohanLarsson** [comment]
Fixed.
