### ISSUE TITLE
REFL003 incorrectly states that internal members do not exist

### ISSUE THREAD

**Issue by jnm2** [DotNetAnalyzers/ReflectionAnalyzers#65]
The member exists in all of these cases:

![image](https://user-images.githubusercontent.com/8040367/45831934-8e362c80-bcce-11e8-98b6-8c3373abfe25.png)

As evidenced by Go To Definition on the type:

![image](https://user-images.githubusercontent.com/8040367/45832000-b6be2680-bcce-11e8-9d61-c3a8d0257a5a.png)

![image](https://user-images.githubusercontent.com/8040367/45832090-fa189500-bcce-11e8-9305-3be7acd07d7a.png)

**Comment by JohanLarsson** [comment]
Looks like [type.GetMembers(name)](http://source.roslyn.codeplex.com/#Microsoft.CodeAnalysis/Symbols/INamespaceOrTypeSymbol.cs,25) does not return nonpublic members not in source.

**Comment by jnm2** [comment]
All four of these are back in 0.1.6-dev exactly as they were in 0.1.4-dev.

**Comment by JohanLarsson** [comment]
Gah, I added tests for them, question is what I dumbed.

**Comment by jnm2** [comment]
They don't show up in the CLI build, though, only in VS with full solution analysis. Maybe it's my end?

**Comment by JohanLarsson** [comment]
Create a new issue with this specific info?

**Comment by jnm2** [comment]
You said in chat I can skip opening that issue in favor of #76, but here is a 0.1.6-dev repro:

```c#
class Repro
{
    public void Test()
    {
        typeof(AggregateException).GetProperty("InnerExceptionCount");
    }
}
```

> REFL003 The type System.AggregateException does not have a member named InnerExceptionCount.
