### ISSUE TITLE
Use GetEvent().Accessor 

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#74]
- [x] `add_X`
- [x] `remove_X`

`raise_X` has no support in C#

Before:
```cs
var addMethod = typeof(Console).GetMethod("add_CancelKeyPress");
```

After:
```cs
var addMethod = typeof(Console).GetEvent(nameof(Console.CancelKeyPress), BindingFlags.Public | BindingFlags.Static | BindingFlags.DeclaredOnly).AddMethod;
```

**Comment by jnm2** [comment]
Alternative to VB is using MetadataBuilder to emit an assembly in memory.

https://github.com/jnm2/ApiContractGenerator/blob/5daf5a2ffe903400f56e730244772728b99be9bf/src/ApiContractGenerator.Tests/Integration/AssemblyReferenceTests.cs#L21-L57
https://github.com/jnm2/ApiContractGenerator/blob/5daf5a2ffe903400f56e730244772728b99be9bf/src/ApiContractGenerator.Tests/Integration/IntegrationTests.cs#L95-L105

**Comment by JohanLarsson** [comment]
Question is if we can use roslyn on the assembly in memory.

**Comment by jnm2** [comment]
Yes. You create an assembly metadata reference from the in-memory emitted stream.

**Comment by JohanLarsson** [comment]
We can create a new issue for `raise_` with this info. Nicer for memory.

**Comment by jnm2** [comment]
Yes. You create an assembly metadata reference from the in-memory emitted stream.

http://source.roslyn.io/#Microsoft.CodeAnalysis/MetadataReference/MetadataReference.cs,cd89ed0fd717f7d1
