### ISSUE TITLE
Generate a table with all nonpublic in the framework?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#76]
We can't see nonpublic members not in source so we can't warn as much as we would like.

#72

**Comment by jnm2** [comment]
For what it's worth, it looks like most of the internal access I've done is in third party libraries.

**Comment by JohanLarsson** [comment]
Yes, the table is not an awesome idea. We should figure out how to do reflection, then we can start answering questions for real.

**Comment by jnm2** [comment]
There's one more sticking point: reference assemblies have no internal or private members, and best practice for a framework is to reference reference assemblies at compile time. So *if* the assembly you resolve has `[assembly: ReferenceAssemblyAttribute]` or is completely missing, I'm still hoping for fallbacks to recognize patterns like `get_` etc.
