### ISSUE TITLE
Should REFL017 nag here?

### ISSUE THREAD

**Issue by JohanLarsson** [DotNetAnalyzers/ReflectionAnalyzers#90]
```cs
typeof(string).GetMethod(nameof(IConvertible.ToInt16))
```

**Comment by jnm2** [comment]
`string` has no public or private method named `ToInt16`, so maybe what the user would have meant was `typeof(IConvertible).GetMethod(nameof(IConvertible.ToInt16))`?

**Comment by JohanLarsson** [comment]
Yes, that is why I'm thinking REFL017 is noise here. We can give a more helpful warning.
